# Generated by Django 3.2.4 on 2021-06-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210614_0043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('ip', 'post')},
        ),
    ]
